name: backup

on:
  schedule:
    # mondays@04:19am
    - cron: "19 4 * * 1"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: chiefbiiko/permalogs3@v0.1.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          BUCKET: permalogs3testingstack-bucket-13p5inhfqasui
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}