name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:0.10.7
        ports:
          - "4572:4572"
        env:
          SERVICES: s3
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - run: npm audit
      - run: npm ci
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: chiefbiiko/poly1305
          AWS_REGION: us-east-1
          BUCKET: permalogs3-testing-bucket
          EXTRA_S3_OPTS: '{"accessKeyId":"abc","secretAccessKey":"xyz","endpoint":"http://127.0.0.1:4572","s3ForcePathStyle":true}'
        run: node ./main.js