name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: us-east-1
      BUCKET: permalogs3testingstack-bucket-13p5inhfqasui
      DEBUG: permalogs3
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: npm audit
      - run: npm ci
      - run: GITHUB_REPOSITORY=chiefbiiko/poly1305 node ./main.js