name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUCKET: permalogs3-testing-bucket
      EXTRA_S3_OPTS: '{"endpoint":"http://localhost:4572"}'
    services:
      localstack:
        image: localstack/localstack:0.10.7
        ports:
          - "4572:4572"
        env:
          SERVICES: s3
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAIOSFODNN7EXAMPLE
          aws-secret-access-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          aws-region: us-east-1
      - run: aws s3 --endpoint-url=http://localhost:4572 mb s3://${{ env.BUCKET }}
      - run: npm audit
      - run: npm ci
      - run: npm test