name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2.0.0
      - name: install node n npm
        uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: audit node modules
        run: npm audit
      - name: install node modules
        run: npm ci
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.1.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: testing permalogs3
        env:
          BUCKET: permalogs3testingstack-bucket-13p5inhfqasui
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # when GITHUB_REPOSITORY=chiefbiiko/permalogs3
          # listRepoWorkflowRuns returns a read error 
          # "Cannot access 'workflow' before initialization"
          GITHUB_REPOSITORY: chiefbiiko/poly1305
        run: npm test